SERVER_NAME: "Development"
MONGO:
  HOST: "127.0.0.1"
  PORT: 27017
  AUTHENTICATION:
    ENABLED: false
    USERNAME: ""
    PASSWORD: ""
REDIS:
  HOST: "127.0.0.1"
  PORT: 6379
  AUTHENTICATION:
    ENABLED: false
    PASSWORD: ""
TAB: true
PUNISHMENTS:
  BROADCAST: "&r{target} &ahas been {context} by &r{sender}"
  BROADCAST_SILENT: "&7[Silent] &r{target} &ahas been {context} by &r{sender}"
  BLACKLIST: "&cYour account is Blacklisted from CentileHCF.\n\n&cThis Punishment cant not be undone."
  BAN:
    KICK: "&cYour account is {context} from CentileHCF.{temporary}\n\n&cIf you feel this punishment is unjust, you may appeal at:\n&ehttps://www.centilehcf.net"
    TEMPORARY: "\n&cThis punishment expires in &e{time-remaining}&c."
  KICK:
    KICK: "&cYou were kicked by a staff member.\nReason: &e{reason}"
COMMON_ERRORS:
  FAILED_TO_LOAD_PROFILE: "&cFailed to load your profile. Try again later."
  COULD_NOT_RESOLVE_PLAYER: "&cCould not resolve player information..."
  PLAYER_NOT_FOUND: "&cA player with that name could not be found."
  RANK_NOT_FOUND: "&cA rank with that name could not be found."
STAFF:
  CHAT: "{0}&r{1}&b ({2}): {3}"
  REQUEST: "&b({0}) {1}: &b({2})"
  BROADCAST_PREFIX: "&9&l[Staff] &r"
  REQUEST_PREFIX: "&9&l[Request] &r"
  JOIN_NETWORK: "{0}{1} &ajoined &2({2})"
  LEAVE_NETWORK: "{0}{1} &aleft &2({2})"
  SWITCH_SERVER: "{0}({1} &ajoined {2} &2(from {3})"
SERVER:
  STATUS: "&b({0}) -> {1}"
  PREFIX: "&9&l[Status] &r"
NETWORK:
  BROADCAST_PREFIX: "&8[&eNetwork&8] &f"
  RANK_REFRESH: "{0} Refreshed rank \"{1}\""
  RANK_DELETE: "{0} Deleted rank \"{1}\""